### ISSUE TITLE
[NoDMs] Suggestion: Customizable Error Message

### ISSUE THREAD

**Issue by maxbooiii** [Obi-Wan3/OB13-Cogs#4]
**Feature Description**

So, currently your `nodms` does not reply to any commands in dms, so what i think would be cool here, is that the bot can reply if you do example `[p]ping` and then bot replies with `No commands can be used in dm` or something like that. it would be amazing, so it doesn't make confusions that the bot doesn't answer to the users who tries to use commands in dms.

**Comment by Obi-Wan3** [comment]
Hey, thanks for this feature request! I agree that it would be useful to be able to set a customizable message to send to users if they attempt to DM the bot, in case of confusion. Right now, I'm thinking of having the bot respond with the message on any command, instead of just specific ones such as `[p]ping`. I'll be working on implementing this when I have time.

**Comment by maxbooiii** [comment]
Awesome, thanks. :D

**Comment by Obi-Wan3** [comment]
@maxbooiii I just implemented this + a few other customizable features in 4caa67603ce59092aeb68b6636084363127531bb .

**Comment by maxbooiii** [comment]
> @maxbooiii I just implemented this + a few other customizable features

Thank you. 😅
